############################################
#   MINECRAFT DOCKER COMPOSE SCRIPT
# ------------------------------------------
#   Dibuat oleh: Muhammad Yudha Abhista (@Yusta)
#   Butuh hosting cepat? Tanpa ribet?
#   https://raznar.id
############################################
services:
  minecraft:
    image: eclipse-temurin:21-jdk-alpine
    ports:
      - 25565:25565
    entrypoint: "/entrypoint.sh"
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app
      - ./scripts/minecraft/entrypoint.sh:/entrypoint.sh

  ngrok:
    image: ngrok/ngrok:alpine
    command: ["start", "--config", "/etc/ngrok.yml", "--all"]
    depends_on:
      - minecraft
    volumes:
      - ./configs/ngrok.yml:/etc/ngrok.yml